using System.Text.Json;
using Microsoft.Agents.AI;
using IncidentTriageAgent.Domain;

namespace IncidentTriageAgent.Services;

public sealed class IncidentTriageService
{
    private static readonly JsonSerializerOptions SerializerOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true
    };

    private readonly AIAgent _structuredWorkflowAgent;
    private readonly AIAgent _textAgent;

    public IncidentTriageService(AIAgent structuredWorkflowAgent, AIAgent textAgent)
    {
        _structuredWorkflowAgent = structuredWorkflowAgent;
        _textAgent = textAgent;
    }

    public async Task<IncidentTriageReport> RunStructuredAsync(string prompt, CancellationToken ct = default)
    {
        var response = await _structuredWorkflowAgent.RunAsync(prompt, cancellationToken: ct);
        var text = GetLastText(response);

        return ParseStructuredReport(text);
    }

    public async Task<string> RunTextAsync(string prompt, CancellationToken ct = default)
    {
        var response = await _textAgent.RunAsync(prompt, cancellationToken: ct);
        return GetLastText(response);
    }

    public async IAsyncEnumerable<string> RunStreamingTextAsync(
        string prompt,
        [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct = default)
    {
        await foreach (var chunk in _textAgent.RunStreamingAsync(prompt, cancellationToken: ct))
        {
            if (!string.IsNullOrWhiteSpace(chunk.Text))
            {
                yield return chunk.Text;
            }
        }
    }

    private static IncidentTriageReport ParseStructuredReport(string response)
    {
        var payload = ExtractJsonObject(response);

        var report = JsonSerializer.Deserialize<IncidentTriageReport>(payload, SerializerOptions);
        if (report is null)
        {
            throw new InvalidOperationException("Model returned an empty structured response.");
        }

        return report;
    }

    private static string ExtractJsonObject(string input)
    {
        var start = input.IndexOf('{');
        var end = input.LastIndexOf('}');

        if (start < 0 || end <= start)
        {
            throw new InvalidOperationException("Structured response did not contain a valid JSON object.");
        }

        return input[start..(end + 1)];
    }

    public static string BuildStructuredInstructions() =>
        """
        You are an Incident Triage Agent for real production operations.

        Your job is to produce practical, safe, and concise incident triage guidance.

        Non-negotiable rules:
        1. Never invent observability data, logs, or metrics that were not provided.
        2. If key information is missing, list it explicitly under missing data.
        3. Prioritize immediate risk reduction and customer impact containment.
        4. Keep actions executable by an on-call engineer.
        5. Use severity levels P1, P2, P3, or P4 only.

        Domain choices:
        - API
        - Database
        - Queue
        - Networking
        - Compute
        - Storage
        - Identity
        - ThirdPartyDependency
        - Unknown

        Return ONLY valid JSON with this exact shape:
        {
          "incidentSummary": "string",
          "severity": "P1|P2|P3|P4",
          "primaryDomain": "API|Database|Queue|Networking|Compute|Storage|Identity|ThirdPartyDependency|Unknown",
          "customerImpact": "string",
          "topLikelyCauses": ["string", "string", "string"],
          "immediateActions15Minutes": ["string", "string", "string"],
          "stabilizationActions60Minutes": ["string", "string", "string"],
          "escalationTargets": ["string", "string"],
          "stakeholderUpdateDraft": "string",
          "missingCriticalData": ["string"]
        }
        """;

    public static string BuildReviewerInstructions() =>
        """
        You are a strict incident triage response reviewer.

        You receive a JSON triage report generated by another agent.
        Validate and correct only these areas:
        1. Severity is one of P1/P2/P3/P4.
        2. Primary domain is one of API/Database/Queue/Networking/Compute/Storage/Identity/ThirdPartyDependency/Unknown.
        3. Action lists are concise and operationally useful.

        Keep the original meaning and avoid inventing facts.
        Return ONLY valid JSON with the same schema as input.
        """;

    public static string BuildTextInstructions() =>
        """
        You are an Incident Triage Agent for real production operations.

        Your job is to produce practical, safe, and concise incident triage guidance.

        Non-negotiable rules:
        1. Never invent observability data, logs, or metrics that were not provided.
        2. If key information is missing, list it explicitly under missing data.
        3. Prioritize immediate risk reduction and customer impact containment.
        4. Keep actions executable by an on-call engineer.
        5. Use severity levels P1, P2, P3, or P4 only.

        Domain choices:
        - API
        - Database
        - Queue
        - Networking
        - Compute
        - Storage
        - Identity
        - ThirdPartyDependency
        - Unknown

        Return concise Markdown.
        """;

    private static string GetLastText(AgentRunResponse response)
    {
        var text = response.Messages.LastOrDefault(m => !string.IsNullOrWhiteSpace(m.Text))?.Text?.Trim();

        if (string.IsNullOrWhiteSpace(text))
        {
            throw new InvalidOperationException("Agent returned an empty response.");
        }

        return text;
    }
}
